import type { Metadata } from "next";
import ServerProviders from "./server-providers";
import ClientsProviders from "./client-providers";

export const metadata: Metadata = {
  title: "PontoSavi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <ServerProviders>
        <ClientsProviders>
          <body>{children}</body>
        </ClientsProviders>
      </ServerProviders>
    </html>
  );
}
